/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.exerciseapp.app.gui;

import com.exerciseapp.app.services.models.Verb;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Adrian
 */
public class ExerciseA extends javax.swing.JDialog {
    
    private List<Integer> pastPos = new ArrayList<>();
    private final Random R = new Random();
    private int pos;
    
    /**
     * Creates new form ExerciseA
     * @param parent
     * @param modal
     */
    public ExerciseA(java.awt.Frame parent, boolean modal) {        
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.pos = this.getNewPosition();
        this.check_btn.setEnabled(false);
        this.next_btn.setEnabled(false);
        System.out.println("pos: " + this.pos);
        this.pastPos.add(this.pos);
        this.meaning_txt.setText(this.getVerbs().get(this.pos).getMeaning());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        verb_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        meaning_txt = new javax.swing.JTextArea();
        result_txt = new javax.swing.JLabel();
        check_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXERCISE A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Type the correct phrasal verb:");

        verb_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        verb_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        verb_txt.setName("verb_txt"); // NOI18N
        verb_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verb_txtActionPerformed(evt);
            }
        });
        verb_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verb_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                verb_txtKeyReleased(evt);
            }
        });

        meaning_txt.setEditable(false);
        meaning_txt.setColumns(20);
        meaning_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        meaning_txt.setRows(5);
        meaning_txt.setName("meaning_txt"); // NOI18N
        jScrollPane1.setViewportView(meaning_txt);

        result_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result_txt.setName("result_txt"); // NOI18N

        check_btn.setText("Check");
        check_btn.setToolTipText("");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verb_txt)
                            .addComponent(result_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verb_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        verb_txt.getAccessibleContext().setAccessibleName("");
        result_txt.getAccessibleContext().setAccessibleName("result_txt");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        this.check();
    }//GEN-LAST:event_check_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        this.next();
    }//GEN-LAST:event_next_btnActionPerformed

    private void verb_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verb_txtKeyPressed
        
    }//GEN-LAST:event_verb_txtKeyPressed

    private void verb_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verb_txtKeyReleased
        String value = this.verb_txt.getText();
        if (!value.trim().isEmpty() && this.verb_txt.isEditable()) {
            this.check_btn.setEnabled(true);
        } else {
            this.check_btn.setEnabled(false);
        }
    }//GEN-LAST:event_verb_txtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verb_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verb_txtActionPerformed
        if (this.check_btn.isEnabled() && !this.next_btn.isEnabled()) {
            this.check();
        } else if (!this.check_btn.isEnabled() && this.next_btn.isEnabled()) {
            this.next();
        }
    }//GEN-LAST:event_verb_txtActionPerformed

    private List<Verb> getVerbs() {
        return Arrays.asList(
                new Verb("Verb 1", "Description 1"),
                new Verb("Verb 2", "Description 2"),
                new Verb("Verb 3", "Description 3"),
                new Verb("Verb 4", "Description 4"),
                new Verb("Verb 5", "Description 5"),
                new Verb("Verb 6", "Description 6"),
                new Verb("Verb 7", "Description 7"),
                new Verb("Verb 8", "Description 8"),
                new Verb("Verb 9", "Description 9"),
                new Verb("Verb 10", "Description 10"),
                new Verb("Verb 11", "Description 11"),
                new Verb("Verb 12", "Description 12"),
                new Verb("Verb 13", "Description 13"),
                new Verb("Verb 14", "Description 14")
        );
    }
    
    private int getNewPosition() {
        return R.nextInt(getVerbs().size());
    }
    
    private void check() {
        String value = this.verb_txt.getText().trim();
        System.out.println("value: " + value);
        
        if (value.equalsIgnoreCase(this.getVerbs().get(this.pos).getVerb())) {
            this.result_txt.setText("Correct!");
            this.result_txt.setForeground(new Color(92, 143, 92));
        } else {
            this.result_txt.setText("Incorrect!");
            this.result_txt.setForeground(Color.RED);
        }
        
        this.next_btn.setEnabled(true);
        this.check_btn.setEnabled(false);
        this.verb_txt.setEditable(false);
    }
    
    private void next() {
        this.result_txt.setText("");
        this.verb_txt.setText("");
        this.check_btn.setEnabled(false);
        
        do {
            if (this.pastPos.size() == this.getVerbs().size()) {
                this.pastPos = new ArrayList<>();
            }
            this.pos = this.getNewPosition();
        } while (this.pastPos.contains(this.pos));
        
        System.out.println("pos: " + this.pos);
        this.meaning_txt.setText(this.getVerbs().get(this.pos).getMeaning());
        this.pastPos.add(this.pos);
        this.next_btn.setEnabled(false);
        this.verb_txt.setEditable(true);
        this.verb_txt.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciseA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciseA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciseA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExerciseA dialog = new ExerciseA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea meaning_txt;
    private javax.swing.JButton next_btn;
    private javax.swing.JLabel result_txt;
    private javax.swing.JTextField verb_txt;
    // End of variables declaration//GEN-END:variables
}
