/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.exerciseapp.app.gui;

import com.exerciseapp.app.services.models.Verb;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Adrian
 */
public class ExerciseB extends javax.swing.JDialog {
    
    private List<Integer> pastPos = new ArrayList<>();
    private final Random R = new Random();
    private int pos;
    
    /**
     * Creates new form ExerciseA
     * @param parent
     * @param modal
     */
    public ExerciseB(java.awt.Frame parent, boolean modal) {        
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.pos = this.getNewPosition();
        this.check_btn.setEnabled(false);
        this.next_btn.setEnabled(false);
        this.word_sp_txt.setEditable(false);
        
        System.out.println("pos: " + this.pos);
        this.pastPos.add(this.pos);
        this.word_sp_txt.setText(this.getWords().get(this.pos).getMeaning());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        word_en_txt = new javax.swing.JTextField();
        result_txt = new javax.swing.JLabel();
        check_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        word_sp_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXERCISE B");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Type the correct word in English:");

        word_en_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        word_en_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        word_en_txt.setName("word_en_txt"); // NOI18N
        word_en_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word_en_txtActionPerformed(evt);
            }
        });
        word_en_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                word_en_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                word_en_txtKeyReleased(evt);
            }
        });

        result_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result_txt.setName("result_txt"); // NOI18N

        check_btn.setText("Check");
        check_btn.setToolTipText("");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        word_sp_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        word_sp_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Word in Spanish:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(word_sp_txt)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(word_en_txt)
                    .addComponent(result_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(word_en_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(word_sp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        word_en_txt.getAccessibleContext().setAccessibleName("");
        result_txt.getAccessibleContext().setAccessibleName("result_txt");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        this.check();
    }//GEN-LAST:event_check_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        this.next();
    }//GEN-LAST:event_next_btnActionPerformed

    private void word_en_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_word_en_txtKeyPressed
        
    }//GEN-LAST:event_word_en_txtKeyPressed

    private void word_en_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_word_en_txtKeyReleased
        String value = this.word_en_txt.getText();
        if (!value.trim().isEmpty() && this.word_en_txt.isEditable()) {
            this.check_btn.setEnabled(true);
        } else {
            this.check_btn.setEnabled(false);
        }
    }//GEN-LAST:event_word_en_txtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void word_en_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word_en_txtActionPerformed
        if (this.check_btn.isEnabled() && !this.next_btn.isEnabled()) {
            this.check();
        } else if (!this.check_btn.isEnabled() && this.next_btn.isEnabled()) {
            this.next();
        }
    }//GEN-LAST:event_word_en_txtActionPerformed

    private List<Verb> getWords() {
        return Arrays.asList(
                new Verb("Word 1", "Palabra 1"),
                new Verb("Word 2", "Palabra 2"),
                new Verb("Word 3", "Palabra 3"),
                new Verb("Word 4", "Palabra 4"),
                new Verb("Word 5", "Palabra 5"),
                new Verb("Word 6", "Palabra 6"),
                new Verb("Word 7", "Palabra 7"),
                new Verb("Word 8", "Palabra 8"),
                new Verb("Word 9", "Palabra 9"),
                new Verb("Word 10", "Palabra 10"),
                new Verb("Word 11", "Palabra 11"),
                new Verb("Word 12", "Palabra 12"),
                new Verb("Word 13", "Palabra 13"),
                new Verb("Word 14", "Palabra 14"),
                new Verb("Word 15", "Palabra 15"),
                new Verb("Word 16", "Palabra 16")
                );
    }
    
    private int getNewPosition() {
        return R.nextInt(getWords().size());
    }
    
    private void check() {
        String value = this.word_en_txt.getText().trim();
        System.out.println("value: " + value);
        
        if (value.equalsIgnoreCase(this.getWords().get(this.pos).getVerb())) {
            this.result_txt.setText("Correct!");
            this.result_txt.setForeground(new Color(92, 143, 92));
        } else {
            this.result_txt.setText("Incorrect!");
            this.result_txt.setForeground(Color.RED);
        }
        
        this.next_btn.setEnabled(true);
        this.check_btn.setEnabled(false);
        this.word_en_txt.setEditable(false);
    }
    
    private void next() {
        this.result_txt.setText("");
        this.word_en_txt.setText("");
        this.check_btn.setEnabled(false);
        
        do {
            if (this.pastPos.size() == this.getWords().size()) {
                this.pastPos = new ArrayList<>();
            }
            this.pos = this.getNewPosition();
        } while (this.pastPos.contains(this.pos));
        
        System.out.println("pos: " + this.pos);
        this.word_sp_txt.setText(this.getWords().get(this.pos).getMeaning());
        this.pastPos.add(this.pos);
        this.next_btn.setEnabled(false);
        this.word_en_txt.setEditable(true);
        this.word_en_txt.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciseB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciseB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciseB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExerciseB dialog = new ExerciseB(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton check_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton next_btn;
    private javax.swing.JLabel result_txt;
    private javax.swing.JTextField word_en_txt;
    private javax.swing.JTextField word_sp_txt;
    // End of variables declaration//GEN-END:variables
}
